### ISSUE TITLE
A pure Julia Technical analysis package

### ISSUE THREAD

**Issue by femtotrader** [femtotrader/TALib.jl#7]
A pure Julia Technical analysis package may also be considered (instead of relying on [TA-Lib](http://ta-lib.org/)

What about
- [TechnicalAnalysis.jl](https://github.com/femtotrader/TechnicalAnalysis.jl)
- TA.jl

**Comment by femtotrader** [comment]
See also
https://github.com/dysonance/Indicators.jl

maybe it could be used to compare results in unit testing

**Comment by femtotrader** [comment]
Maybe on the other side, [TALib.jl](https://github.com/femtotrader/TALib.jl) could be use to compare results of [Indicators.jl](https://github.com/dysonance/Indicators.jl)
Pinging @dysonance

**Comment by JTAmos** [comment]
@femtotrader Already talked about this briefly in the mentioned issue above, but yeah I did work fairly extensively on trying to replicate much of the functionality in TA-Lib in pure Julia. As I haven't made use of TA-Lib in quite some time, if there's something in there that you feel is missing, please throw up a GitHub issue and I (or we) can get cracking on implementing it!

**Comment by femtotrader** [comment]
Closing as we also have now [IncTA.jl](https://github.com/femtotrader/IncTA.jl).
